CREATE DATABASE IF NOT EXISTS accountsdb;
CREATE DATABASE IF NOT EXISTS loansdb;
CREATE DATABASE IF NOT EXISTS cardsdb;

CREATE USER IF NOT EXISTS 'vishal'@'%' IDENTIFIED BY 'i2ig6swq';

GRANT ALL PRIVILEGES ON accountsdb.* TO 'vishal'@'%';
GRANT ALL PRIVILEGES ON loansdb.* TO 'vishal'@'%';
GRANT ALL PRIVILEGES ON cardsdb.* TO 'vishal'@'%';

FLUSH PRIVILEGES;